services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    # No ports mapping for back-end

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    # No ports mapping for front-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: nginx-proxy:task6
    ports:
      - "80:80"  # Map container's port 80 to host's port 80
    depends_on:
      - front-end
      - back-end
